
# # This is a basic workflow to help you get started with Actions

# name: Deploy to ECR

# # Controls when the workflow will run
# on:
#   # Triggers the workflow on push or pull request events but only for the master branch
#   push:
#     branches: [ main ]

# jobs:
  
#   build:
    
#     name: Build Image
#     runs-on: self-hosted

#     # Steps represent a sequence of tasks that will be executed as part of the job
#     steps:

#     - name: Check out code
#       uses: actions/checkout@v2
    
#     - name: Configure AWS credentials
#       env:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: us-east-1

#     - name: Login to Amazon ECR
#       id: login-ecr
#       uses: aws-actions/amazon-ecr-login@v1

#     - name: Build, tag, and push image to Amazon ECR
#       env:
#         ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
#         ECR_REPOSITORY: docker-nodejs-app
#         IMAGE_TAG: latest
#       run: |
#         docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
#         docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

# name: publish
# on: [push]
# jobs:
#   publish-hello-docker-image:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@v2
#       echo  | docker login ghcr.io -u balu1391 --password-stdin

#     - name: Login to GitHub Container Registry
#       env :
#         username: ${{ github.actor }}
#         password: ${{ secrets.GITHUB_TOKEN }}
#     - name: Build the hello-docker Docker image
#       run: |
#          echo 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 | docker login ghcr.io -u balu1391 --password-stdin
#          docker build . --tag ghcr.io/deselikem/hello-docker-gcr-demo:latest
#          docker run ghcr.io/deselikem/hello-docker-gcr-demo:latest
#          docker push ghcr.io/deselikem/hello-docker-gcr-demo:latest

name: publish

on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
    - name: Git checkout
      uses: actions/checkout@v2
    - name: Build the hello-docker Docker image
      run: |
       docker login ghcr.io -u balu1391 -p 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
       docker build . --tag ghcr.io/balu1391/hello-docker-gcr-demo:latest
       docker run ghcr.io/balu1391/hello-docker-gcr-demo:latest
       docker push ghcr.io/balu1391/hello-docker-gcr-demo:latest
